### ISSUE TITLE
Add a user profile API endpoint

### ISSUE THREAD

**Issue by vicky5124** [PolyTech-Modding/PolyMod#24]
add an endpoint to get the user information from a cookie or token.
it will be `/me` and it will return a json with the user information, that will include a list of roles, and the ban status for now.
later will have mods owned by that account and the teams the user is part of.

**Comment by Conqu3red** [comment]
Could this endpoint return the username and discriminator also?

**Comment by vicky5124** [comment]
Blocked by #7

**Comment by vicky5124** [comment]
Fixed on #bbbb80e
